---
version: '3.4'

services: 
  front-apache:
    image: webdevops/php-apache
    container_name: php-apache
    ports:
      - "8002:80"
    volumes:
      - local_data:/app:ro
  front-nginx: 
    image: nginx
    container_name: php-nginx
    ports:
      - "8001:80"
    volumes:
      - local_data:/usr/share/nginx/html:ro
volumes:
  local_data:
    external: 
      name: data
# docker volume create --driver local --opt type=none --opt device=`pwd`/app --opt o=bind data